language: csharp
mono: none
dotnet: 2.1.300
script:
  - dotnet restore
  - dotnet build
  - sonar-scanner
env:
  global:
    secure: "g8n4SJRytCXt3dyA7CZZJIeDTbcsnUmtdtOJcYn+LTh1ZzDXydY0JUvPnBPBX/kP/9JlBX/wLShDWeW84CwJtFITiNWHXgLYdr/d54BtwT7RZVCz5XaguHRhPKOhYPtuBLNNFsl7t301SJd2yBKmJ3+Rm8sR+5KalESVwmMceBUEupNZcdE1jgXxU6FBLqEvGlcXBvWO3bq+kExyCVX5iqI57GGXPxAEhh4EzV7DHsSjK6aLZXzJv3rYsWqp8QVSIzCDSwVlMPM4emwFnMNguG2VYBh7WM+HWMlDLiwoC7CvffJrXnW1BkCOA0LSv0if+YJpEZ2V36BMGa3uS9NwxlIApI3hx4smPWD96zqzYsjK6xwmAnZ+XNHUB/Yom0WH2ebj7J7hPpDy6+EjH2nvP1FeiF57XvyA/oyF/99tHShYK2iIYy49Q9M5Nk7mUfESJuv9BpctJ+uK5li1wOOXV+eHbv2uCE0Ng7Z54k1lehiGC/BFB1G97WFygACd8v9l13PkzMcIOU77p8U/ETrE4Y1NjP9H3axeMAuEc+XUU+Cgg72OKpn2leD5Kqjv6FEVi58YmS/bSGE4NqCoT9QcHiMGIsxMetR+ewa+9QyK2JdyqDF2inqwdNI52sww6iweer7wNzEtSjRYHggbEp4UepXPca0YlzXqLO/MT67YshQ="
dist: trusty
addons:
  sonarcloud:
    organization: "ironiclensflare"
    token:
      secure: "g8n4SJRytCXt3dyA7CZZJIeDTbcsnUmtdtOJcYn+LTh1ZzDXydY0JUvPnBPBX/kP/9JlBX/wLShDWeW84CwJtFITiNWHXgLYdr/d54BtwT7RZVCz5XaguHRhPKOhYPtuBLNNFsl7t301SJd2yBKmJ3+Rm8sR+5KalESVwmMceBUEupNZcdE1jgXxU6FBLqEvGlcXBvWO3bq+kExyCVX5iqI57GGXPxAEhh4EzV7DHsSjK6aLZXzJv3rYsWqp8QVSIzCDSwVlMPM4emwFnMNguG2VYBh7WM+HWMlDLiwoC7CvffJrXnW1BkCOA0LSv0if+YJpEZ2V36BMGa3uS9NwxlIApI3hx4smPWD96zqzYsjK6xwmAnZ+XNHUB/Yom0WH2ebj7J7hPpDy6+EjH2nvP1FeiF57XvyA/oyF/99tHShYK2iIYy49Q9M5Nk7mUfESJuv9BpctJ+uK5li1wOOXV+eHbv2uCE0Ng7Z54k1lehiGC/BFB1G97WFygACd8v9l13PkzMcIOU77p8U/ETrE4Y1NjP9H3axeMAuEc+XUU+Cgg72OKpn2leD5Kqjv6FEVi58YmS/bSGE4NqCoT9QcHiMGIsxMetR+ewa+9QyK2JdyqDF2inqwdNI52sww6iweer7wNzEtSjRYHggbEp4UepXPca0YlzXqLO/MT67YshQ="  
